// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQUAeWQBvLekNV026CHcpTseE9Ycl7y4',
    appId: '1:876597069023:web:90bd73008388ff8c24956a',
    messagingSenderId: '876597069023',
    projectId: 'sensoresfca',
    authDomain: 'sensoresfca.firebaseapp.com',
    storageBucket: 'sensoresfca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvoMEem8IH22j3QlYyCcIz2kCB4S8gvU',
    appId: '1:876597069023:android:3c0132e4f739ba0824956a',
    messagingSenderId: '876597069023',
    projectId: 'sensoresfca',
    storageBucket: 'sensoresfca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC51lRbe5hSiHI4Ox5ZS1VHNPbditY_EZg',
    appId: '1:876597069023:ios:0ae10fdb69acba1a24956a',
    messagingSenderId: '876597069023',
    projectId: 'sensoresfca',
    storageBucket: 'sensoresfca.firebasestorage.app',
    iosBundleId: 'com.elbservicios.sensagro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC51lRbe5hSiHI4Ox5ZS1VHNPbditY_EZg',
    appId: '1:876597069023:ios:0ae10fdb69acba1a24956a',
    messagingSenderId: '876597069023',
    projectId: 'sensoresfca',
    storageBucket: 'sensoresfca.firebasestorage.app',
    iosBundleId: 'com.elbservicios.sensagro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkQUAeWQBvLekNV026CHcpTseE9Ycl7y4',
    appId: '1:876597069023:web:1ca4e18992f40d0424956a',
    messagingSenderId: '876597069023',
    projectId: 'sensoresfca',
    authDomain: 'sensoresfca.firebaseapp.com',
    storageBucket: 'sensoresfca.firebasestorage.app',
  );
}
